### ISSUE TITLE
switchの運動結果の収集

### ISSUE THREAD

**Issue by 42zoko9** [42zoko9/dieter#3]
リングフィットアドベンチャー及びフィットボクシングの結果を収集しgcs上にまとめたい

switch - (Twitter連携で手動アップロード)-> Twitter -(実装)-> gcs

実装部分がやるべきタスク

**Comment by 42zoko9** [comment]
フィットボクシングの結果はfitbitにエアロビクスとしてログが残るため，一先ずはリングフィットの結果のみを収集する

**Comment by 42zoko9** [comment]
作業進捗 https://github.com/42zoko9/dieter/commit/b1236003d18a29481fe063b1f10302568666f765

一先ずデプロイしてみてちゃんと動いているか確認してみる

**Comment by 42zoko9** [comment]
下記によりcrashしていた
```
2021-11-26T16:00:16.167Zdieterrrqoj6yg0gbf Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 24, in main run(GCP_PROJECT) File "/workspace/main.py", line 160, in run urllib.request.urlretrieve(u, figure_path) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 257, in urlretrieve tfp = open(filename, 'wb') FileNotFoundError: [Errno 2] No such file or directory: '/tmp/data/ring_fit_adventure/2021-11-26_FFHIp79VgAAQdMw.jpg'
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 24, in main run(GCP_PROJECT) File "/workspace/main.py", line 160, in run urllib.request.urlretrieve(u, figure_path) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 257, in urlretrieve tfp = open(filename, 'wb') FileNotFoundError: [Errno 2] No such file or directory: '/tmp/data/ring_fit_adventure/2021-11-26_FFHIp79VgAAQdMw.jpg'
```


https://github.com/42zoko9/dieter/commit/73603728ccfc9fe0b24de6ba0e7d4a2a11da0c76 の修正を行い再ビルド

**Comment by 42zoko9** [comment]
動作確認完了
