### ISSUE TITLE
Cloud Functions下におけるiniファイルの編集

### ISSUE THREAD

**Issue by 42zoko9** [42zoko9/dieter#5]
2021-11-10T16:00:08.705Zに発生
```
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 20, in main run(GCP_PROJECT) File "/workspace/main.py", line 68, in run fb.export_config(ini_path) File "/workspace/src/fitbit.py", line 247, in export_config with open(path, 'w') as configfile: OSError: [Errno 30] Read-only file system: 'config.ini'
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 20, in main run(GCP_PROJECT) File "/workspace/main.py", line 68, in run fb.export_config(ini_path) File "/workspace/src/fitbit.py", line 247, in export_config with open(path, 'w') as configfile: OSError: [Errno 30] Read-only file system: 'config.ini'
```

原因はconfig.iniファイルの上書きが失敗したものと思われる

**Comment by 42zoko9** [comment]
下記のコミットにて対応，明日の自動実行結果を確認  
https://github.com/42zoko9/dieter/commit/270ae31e5ac805460c4b3e75c6381a57318a7264

**Comment by 42zoko9** [comment]
fitbitのデータ取得にてコケている，認証周りのデータの受け取り方を変更する必要あり
```
2021-11-16T16:00:08.268Zdieterkst0nfrqfp6z Traceback (most recent call last): File "/workspace/main.py", line 67, in run data = fb.fetch_trace_data(c, day_str) File "/workspace/src/fitbit.py", line 98, in fetch_trace_data raise e File "/workspace/src/fitbit.py", line 94, in fetch_trace_data with urllib.request.urlopen(req) as res: File "/opt/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/opt/python3.8/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 401: Unauthorized
Traceback (most recent call last): File "/workspace/main.py", line 67, in run data = fb.fetch_trace_data(c, day_str) File "/workspace/src/fitbit.py", line 98, in fetch_trace_data raise e File "/workspace/src/fitbit.py", line 94, in fetch_trace_data with urllib.request.urlopen(req) as res: File "/opt/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/opt/python3.8/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

```
2021-11-16T16:00:08.268Zdieterkst0nfrqfp6z Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 21, in main run(GCP_PROJECT) File "/workspace/main.py", line 73, in run os.remove(ini_path) OSError: [Errno 30] Read-only file system: 'config.ini'
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 21, in main run(GCP_PROJECT) File "/workspace/main.py", line 73, in run os.remove(ini_path) OSError: [Errno 30] Read-only file system: 'config.ini'
```

**Comment by 42zoko9** [comment]
GCP環境下ではiniファイルを更新しないように変更，それに追従してトークンのリフレッシュ時にrefresh_tokenの値を更新も止めるように変更
https://github.com/42zoko9/dieter/commit/afee7066e62c7a005d51e22fddfb1c180041442a

**Comment by 42zoko9** [comment]
refresh_tokenの更新でコケてしまっている，原因はrefresh_tokenの期限切れ？
もう１度refresh_tokenを更新してビルドを試みる

```
2021-11-18T16:00:08.600Zdieter01y3jtz3x011 Traceback (most recent call last): File "/workspace/main.py", line 66, in run data = fb.fetch_trace_data(c, day_str) File "/workspace/src/fitbit.py", line 98, in fetch_trace_data raise e File "/workspace/src/fitbit.py", line 94, in fetch_trace_data with urllib.request.urlopen(req) as res: File "/opt/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/opt/python3.8/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 401: Unauthorized
Traceback (most recent call last): File "/workspace/main.py", line 66, in run data = fb.fetch_trace_data(c, day_str) File "/workspace/src/fitbit.py", line 98, in fetch_trace_data raise e File "/workspace/src/fitbit.py", line 94, in fetch_trace_data with urllib.request.urlopen(req) as res: File "/opt/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/opt/python3.8/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

```
2021-11-18T16:00:08.600Zdieter01y3jtz3x011 Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 20, in main run(GCP_PROJECT) File "/workspace/main.py", line 69, in run fb.refresh_access_token() File "/workspace/src/fitbit.py", line 163, in refresh_access_token raise e File "/workspace/src/fitbit.py", line 159, in refresh_access_token with urllib.request.urlopen(req) as res: File "/opt/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/opt/python3.8/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 400: Bad Request
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 20, in main run(GCP_PROJECT) File "/workspace/main.py", line 69, in run fb.refresh_access_token() File "/workspace/src/fitbit.py", line 163, in refresh_access_token raise e File "/workspace/src/fitbit.py", line 159, in refresh_access_token with urllib.request.urlopen(req) as res: File "/opt/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/opt/python3.8/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/opt/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by 42zoko9** [comment]
APIのアクセス情報をkmsで管理することを止め，secret managerに移行
https://github.com/42zoko9/dieter/commit/fd5ac0f1495483fef6c519b4443d84c5db410cb1

**Comment by 42zoko9** [comment]
https://github.com/42zoko9/dieter/pull/8 より解決
